In [2]:
from array import *

In [10]:
arr = array('i', [1,2,3,4])
print(arr)
print(arr.buffer_info())
arr.append(5)
print(arr)
arr.insert(2,12)
print(arr)

array('i', [1, 2, 3, 4])
(140283850810672, 4)
array('i', [1, 2, 3, 4, 5])
array('i', [1, 2, 12, 3, 4, 5])


In [2]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [14]:
np.array(24)

array(24)

In [15]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr = np.array([[[1,2,3], [4,5,6]]])
print(arr.ndim)

3


In [24]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr.ndim, arr)

5 [[[[[1 2 3 4 5]]]]]


In [30]:
arr = np.array([1.1,2.1,3.1,4.4])
newarr = arr.astype('i')
print(newarr)

[1 2 3 4]


In [35]:
arr = np.array([[1,2,3], [4,5,6]])
arr.shape

(2, 3)

In [9]:
arr = np.array([i for i in range(12)]).reshape(3,4)
print(arr.shape[1])

4


In [11]:
import pandas as pd


In [16]:
a = {
    'val' : [1,2,3,4,5],
    'name': ['a', 'b', 'c', 'd', 'e']
}
pd.Series(a)

val     [1, 2, 3, 4, 5]
name    [a, b, c, d, e]
dtype: object

In [38]:
f = pd.DataFrame(a, index=['a', 'b', 'c', 'd', 'e'])
print(f)
print(f.loc[['a', 'c', 'e']])

   val name
a    1    a
b    2    b
c    3    c
d    4    d
e    5    e
   val name
a    1    a
c    3    c
e    5    e


In [68]:
a = {
    'val' : [1,2,3,4,5, None],
    'name': [None, None, 1, 2, None, None],
    'sal' : [None, 200, None, None, None, None]
}
f = pd.DataFrame(a)
print(f)
print(f.dropna(axis=0, thresh=2))

   val  name    sal
0  1.0   NaN    NaN
1  2.0   NaN  200.0
2  3.0   1.0    NaN
3  4.0   2.0    NaN
4  5.0   NaN    NaN
5  NaN   NaN    NaN
   val  name    sal
1  2.0   NaN  200.0
2  3.0   1.0    NaN
3  4.0   2.0    NaN


In [69]:
a = {
    'val' : [1,2,3,4,5, None],
    'name': [None, None, 1, 2, None, None],
    'sal' : [None, 200, None, None, None, None]
}
f = pd.DataFrame(a)
print(f)
print(f.dropna(axis=0, subset=['val']))

df = pd.read_csv('BCancer.csv')
df = df.iloc[:, 1:-1]

   val  name    sal
0  1.0   NaN    NaN
1  2.0   NaN  200.0
2  3.0   1.0    NaN
3  4.0   2.0    NaN
4  5.0   NaN    NaN
5  NaN   NaN    NaN
   val  name    sal
0  1.0   NaN    NaN
1  2.0   NaN  200.0
2  3.0   1.0    NaN
3  4.0   2.0    NaN
4  5.0   NaN    NaN


In [90]:
df.corr()

radius_mean  texture_mean  smoothness_mean  \
radius_mean                 1.000000      0.323782         0.170581   
texture_mean                0.323782      1.000000        -0.023389   
smoothness_mean             0.170581     -0.023389         1.000000   
compactness_mean            0.506124      0.236702         0.659123   
concavity_mean              0.676764      0.302418         0.521984   
concave points_mean         0.822529      0.293464         0.553695   
symmetry_mean               0.147741      0.071401         0.557775   
fractal_dimension_mean     -0.311631     -0.076437         0.584792   
radius_se                   0.679090      0.275869         0.301467   
texture_se                 -0.097317      0.386358         0.068406   
perimeter_se                0.674172      0.281673         0.296092   
area_se                     0.735864      0.259845         0.246552   
smoothness_se              -0.222600      0.006614         0.332375   
compactness_se              0.206000      0.191975         0.318943   
concavity_se                0.194204      0.143293         0.248396   
concave points_se           0.376169      0.163851         0.380676   
symmetry_se                -0.104321      0.009127         0.200774   
fractal_dimension_se       -0.042641      0.054458         0.283607   
radius_worst                0.969539      0.352573         0.213120   
texture_worst               0.297008      0.912045         0.036072   
perimeter_worst             0.965137      0.358040         0.238853   
area_worst                  0.941082      0.343546         0.206718   
smoothness_worst            0.119616      0.077503         0.805324   
compactness_worst           0.413463      0.277830         0.472468   
concavity_worst             0.526911      0.301025         0.434926   
concave points_worst        0.744214      0.295316         0.503053   
symmetry_worst              0.163953      0.105008         0.394309   
fractal_dimension_worst     0.007066      0.119205         0.499316   

                         compactness_mean  concavity_mean  \
radius_mean                      0.506124        0.676764   
texture_mean                     0.236702        0.302418   
smoothness_mean                  0.659123        0.521984   
compactness_mean                 1.000000        0.883121   
concavity_mean                   0.883121        1.000000   
concave points_mean              0.831135        0.921391   
symmetry_mean                    0.602641        0.500667   
fractal_dimension_mean           0.565369        0.336783   
radius_se                        0.497473        0.631925   
texture_se                       0.046205        0.076218   
perimeter_se                     0.548905        0.660391   
area_se                          0.455653        0.617427   
smoothness_se                    0.135299        0.098564   
compactness_se                   0.738722        0.670279   
concavity_se                     0.570517        0.691270   
concave points_se                0.642262        0.683260   
symmetry_se                      0.229977        0.178009   
fractal_dimension_se             0.507318        0.449301   
radius_worst                     0.535315        0.688236   
texture_worst                    0.248133        0.299879   
perimeter_worst                  0.590210        0.729565   
area_worst                       0.509604        0.675987   
smoothness_worst                 0.565541        0.448822   
compactness_worst                0.865809        0.754968   
concavity_worst                  0.816275        0.884103   
concave points_worst             0.815573        0.861323   
symmetry_worst                   0.510223        0.409464   
fractal_dimension_worst          0.687382        0.514930   

                         concave points_mean  symmetry_mean  \
radius_mean                         0.822529       0.147741   
texture_mean                        0.293464       0.071401   
smooth

In [95]:
df[['diagnosis', 'radius_mean']]

diagnosis  radius_mean
0           M        17.99
1           M        20.57
2           M        19.69
3           M        11.42
4           M        20.29
..        ...          ...
564         M        21.56
565         M        20.13
566         M        16.60
567         M        20.60
568         B         7.76

[569 rows x 2 columns]

In [98]:
df.iloc[564, 0]

'M'